version: '3'
services:
  onlineconf-updater:
    build: .
    image: onlineconf-updater
    volumes:
      - ./data:/usr/local/etc/onlineconf
    environment:
      ONLINECONF_ADMIN_HOST: oc.localhost
      ONLINECONF_ADMIN_PORT: 80
      ONLINECONF_UPDATER_USER: new
      ONLINECONF_UPDATER_PASSWORD: pass
    restart: always
networks:
  bridge:
    external: true
#      name: admin_default
