version: '3'
services:
  onlineconf-admin:
    build: .
    image: onlineconf-admin
    pull_policy: build
    depends_on:
      onlineconf-database:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    environment:
      ONLINECONF_DATABASE_HOST: onlineconf-database
      ONLINECONF_DATABASE_BASE: onlineconf
      ONLINECONF_DATABASE_USER: onlineconf
      ONLINECONF_DATABASE_PASSWORD: onlineconf
    restart: always
  onlineconf-database:
    image: mysql:8.0
    volumes:
      - data:/var/lib/mysql
      - ./etc/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./etc/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./etc/notification.sql:/docker-entrypoint-initdb.d/2-notification.sql
      - ./etc/auth.sql:/docker-entrypoint-initdb.d/3-auth.sql
      - ./etc/example-auth.sql:/docker-entrypoint-initdb.d/4-example-auth.sql
      - ./etc/example-with-projects.sql:/docker-entrypoint-initdb.d/5-example.sql
      #- ./etc/example-wo-projects.sql:/docker-entrypoint-initdb.d/5-example.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: onlineconf
      MYSQL_USER: onlineconf
      MYSQL_PASSWORD: onlineconf
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      interval: 1s
      retries: 60
volumes:
  data: {}
