services:
  onlineconf-admin:
    image: ghcr.io/nikolo/onlineconf-admin:03daa51
    depends_on:
      onlineconf-database:
        condition: service_healthy
    environment:
      ONLINECONF_DATABASE_HOST: onlineconf-database
      ONLINECONF_DATABASE_BASE: onlineconf
      ONLINECONF_DATABASE_USER: onlineconf
      ONLINECONF_DATABASE_PASSWORD: onlineconf
      ONLINECONF_AUTH_HEADER: ${AUTH_HEADER_NAME:-X-Username}
    restart: always
    volumes:
      - staticshare:/var/www/onlineconf-admin
  onlineconf-database:
    image: mysql:8.0
    volumes:
      - data:/var/lib/mysql
      - ./etc/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./etc/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./etc/notification.sql:/docker-entrypoint-initdb.d/2-notification.sql
      - ./etc/auth.sql:/docker-entrypoint-initdb.d/3-auth.sql
      - ./etc/example-auth.sql:/docker-entrypoint-initdb.d/4-example-auth.sql
      - ./etc/example-with-projects.sql:/docker-entrypoint-initdb.d/5-example.sql
      #- ./etc/example-wo-projects.sql:/docker-entrypoint-initdb.d/5-example.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: onlineconf
      MYSQL_USER: onlineconf
      MYSQL_PASSWORD: onlineconf
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      interval: 1s
      retries: 60
  onlineconf-nginx:
    image: nginx:stable
    volumes:
      - ./etc/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./etc/nginx.htpasswd:/usr/share/nginx/.htpasswd:ro # docker run --rm --entrypoint htpasswd registry:2.7.0 -Bbn admin admin > etc/nginx.htpasswd
      - staticshare:/usr/local/www/onlineconf
    ports:
      - "8010:80"
    environment:
      - NGINX_PORT=80
      - NGINX_ADMIN_HOST=onlineconf-admin
      - NGINX_AUTH_HEADER_NAME=${AUTH_HEADER_NAME:-X-Username}
    depends_on:
      - onlineconf-admin
volumes:
  data: {}
  staticshare:
    driver: local
