name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'updater/**'
      - '.github/workflows/main.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        cd updater && docker build -t ghcr.io/nikolo/onlineconf-updater:latest .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Push Docker image
      run: |
        docker push ghcr.io/nikolo/onlineconf-updater:latest
