name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'updater/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker buildx build \
          --tag ghcr.io/${{ github.repository_owner }}/onlineconf-updater:latest \
          --file updater/Dockerfile \
          --context updater \
          .

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker buildx build \
          --tag ghcr.io/${{ github.repository_owner }}/onlineconf-updater:latest \
          --push \
          --file updater/Dockerfile \
          --context updater \
          .
