name: Build and Push Docker Image

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - "updater/**"
      - ".github/workflows/updater-*.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd updater && docker build -t ghcr.io/${{ github.action_repository }}-updater:$COMMIT_SHORT_SHA .

  push:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.action_repository }}-updater:$COMMIT_SHORT_SHA
