name: Release new updater version

on:
  push:
    tags:
      - onlineconf-updater/v*

jobs:
  updater-make-latest:
    runs-on: ubuntu-latest
    concurrency:
      group: updater-tag-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/$REPO-updater:$COMMIT_SHORT_SHA

      - name: Tag Docker image
        run: |
          docker image tag ghcr.io/$REPO-updater:$COMMIT_SHORT_SHA ghcr.io/$REPO-updater:latest
